name: Destroy

on:
  workflow_dispatch:    # Dispatch workflow trigger can also be used for releases
    inputs:
      environment:
        type: choice
        description: Which environment to remove AWS resources for?
        options:
          - staging
          - prod   # This is for a demo, best practice prod should not be included incase of accidental delete

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Terraform Destroy
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export TF_WORKSPACE=${{ github.event.inputs.environment }}
          cd infra/
          docker compose run --rm terraform -chdir=deploy/ init
          docker compose run --rm terraform -chdir=deploy/ destroy -auto-approve
